spring.application.name=bookmyshow

# ========== DATABASE CONFIGURATION ==========
#spring.datasource.url = jdbc:postgresql://localhost:5432/movie
#spring.datasource.username = postgres
#spring.datasource.password = postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA / Hibernate Config (optional but recommended)
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

jwt.JwSecretKey=kYz6@3s9A8v4!LxQ5KdM#b6H$kM8Zr9PfG1D2hL5Nb4JxW6Uz!eC2T8GjVfQsM3E
jwt.JwExpirationMs=3600000

# Maximum size of a single file
spring.servlet.multipart.max-file-size=10MB

# Maximum size of the entire request (all parts combined)
spring.servlet.multipart.max-request-size=10MB


