trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '22.14.0'
  java_version: '21'

stages:
  - stage: Build_Backend
    displayName: "Build Spring Boot Backend"
    jobs:
      - job: BuildJava
        steps:
          # Use Java 21
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'